# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-18 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20180118_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='home', max_length=120),
        ),
    ]
